version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./images:/app/images
    environment:
      - FLASK_ENV=development
    command: python app.py
